### ISSUE TITLE
This is a very good idea, I hope you continue development

### ISSUE THREAD

**Issue by faddat** [syllabix/go-commerce#1]
We need a golang e-commerce system.  It's good thinking, and strategically timed well.

**Comment by syllabix** [comment]
I agree. The work I started on git hub has actually continued and will be
launched june 1 for www.harvestbox.com. As the code spends some time in
production, I will look to get an open source version out on github
- tom

**Comment by Ramshackle-Jamathon** [comment]
Give us the source code Bro.

Let us drink of those sweet nectars.

**Comment by aerth** [comment]
@syllabix site looks good!  :dancers:
